client_id :  'xxxxxxx'
client_secret : 'xxxxxxxxx'
refresh_token : 'None'
protocol : 'https'
domain : 'io.catchpoint.com/ui/api'
token_endpoint: 'token'
version : 'v1'
rawdata_endpoint : 'performance/raw?tests'
test_ids: { 
            #   web : ['123456','123456',''123456'],
            #   traceroute : [], 
            #   api : [],
            #   transaction: [],
            #   dns : [],
            #   smtp : ['],
            #   websocket: [],
            #   ping : [']
              
          }
# get_logger  
batch_size : 10
log_file : 'app.log'
log_level : 'debug'
